[features]
seeds = false
skip-lint = false
[programs.localnet]
renec_dapp_template = "2DGkbVKhZsSjmygWkPhfJDYdDwmDKy7wHfKVaNgPdu3e"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
